#!/bin/sh

set -eu

image=$(readlink -e "$1")
outputdir="$HOME/.cache/sqim$image"

mkdir -p "$outputdir"
cd "$outputdir"

if [ ! "$image" -ot  "thumbnail.png" ]; then
    convert \
        -background Gray \
        -thumbnail '50x50>' \
        -extent 50x50 \
        -gravity center \
        "$image" thumbnail.png
fi

echo "$outputdir/thumbnail.png"
